name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '45 10 * * *'
  push:
    paths-ignore:
      - '*.md'

env:
  IMAGE_NAME: joniator/youtube-dlp
  DESCRIPTION: youtube-dlp image based on alpine 3

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Set buildx and QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against ghcr
      - name: Log into ghcr
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login against docker hub
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image with Buildx 
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: localimage:test

      # Get latest version
      - name: Get latest version
        id: get_version
        run: |
          sh .github/workflows/get_version.sh

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.get_version.outputs.version }}
          labels: |
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      # Build Docker image with Buildx 
      - name: Push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker-Hub README
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: ${{ env.IMAGE_NAME }}
          description: ${{ env.DESCRIPTION }}
